pipeline {
    agent any 
    tools {
      jdk 'jdk-17'
      gradle 'gradle_8.7'
    }
 environment {
      DOCKERHUB_CREDENTIALS = credentials('DOCKER_HUB_TOKEN') 
  }
  stages {
    stage('Checkout Application Git Branch') {
        steps {
            git credentialsId: 'GITLAB_USER_TOKEN',
                url: 'https://lab.ssafy.com/s10-final/S10P31E106.git',
                branch: 'feat/jenkins'
        }
        post {
                failure {
                  echo 'Repository clone failure !'
                }
                success {
                  echo 'Repository clone success !'
                }
        }
    }
    stage('gardle Jar Build') {
            steps {
                dir('./backend/connectus') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean'
                    sh './gradlew bootjar' 
                }
            }
            post {
                    failure {
                      echo 'Gradle jar build failure !'
                    }
                    success {
                      echo 'Gradle jar build success !'
                    }
            }
    }
    stage('Docker Image Build (1) : Apigateway') {
            steps {
                dir('./backend/connectus/apigateway-service') {
                  sh 'sudo docker build . -t jinjoo0402/connectus_apigateway:latest'
                }
            }
            post {
                    failure {
                      echo 'Apigateway docker image ${currentBuild.number} build failure !'
                    }
                    success {
                      echo 'Apigateway docker image ${currentBuild.number} build success !'
                    }
            }
    }
    stage('Docker Image Build (2) : Discovery') {
            steps {
                dir('./backend/connectus/discovery-service') {
                  sh 'sudo docker build . -t jinjoo0402/connectus_discovery:latest'
                }
            }
            post {
                    failure {
                      echo 'Discovery docker image ${currentBuild.number} build failure !'
                    }
                    success {
                      echo 'Discovery docker image ${currentBuild.number} build success !'
                    }
            }
    }
    stage('Docker Image Build (3) : Event') {
            steps {
                dir('./backend/connectus/event-service') {
                  sh 'sudo docker build . -t jinjoo0402/connectus_event:latest'
                }
            }
            post {
                    failure {
                      echo 'Event docker image ${currentBuild.number} build failure !'
                    }
                    success {
                      echo 'Event docker image ${currentBuild.number} build success !'
                    }
            }
    }
    stage('Docker Image Build (4) : Gather') {
            steps {
                dir('./backend/connectus/gather-service') {
                  sh 'sudo docker build . -t jinjoo0402/connectus_gather:latest'
                }
            }
            post {
                    failure {
                      echo 'Gather docker image ${currentBuild.number} build failure !'
                    }
                    success {
                      echo 'Gather docker image ${currentBuild.number} build success !'
                    }
            }
    }
    stage('Docker Image Build (5) : Likes') {
            steps {
                dir('./backend/connectus/likes-service') {
                  sh 'sudo docker build . -t jinjoo0402/connectus_likes:latest'
                }
            }
            post {
                    failure {
                      echo 'Likes docker image ${currentBuild.number} build failure !'
                    }
                    success {
                      echo 'Likes docker image ${currentBuild.number} build success !'
                    }
            }
    }
    stage('Docker Image Build (6) : Post') {
            steps {
                dir('./backend/connectus/post-service') {
                  sh 'sudo docker build . -t jinjoo0402/connectus_post:latest'
                }
            }
            post {
                    failure {
                      echo 'Post docker image ${currentBuild.number} build failure !'
                    }
                    success {
                      echo 'Post docker image ${currentBuild.number} build success !'
                    }
            }
    }
    stage('Docker Image Build (7) : Spot') {
            steps {
                dir('./backend/connectus/spot-service') {
                  sh 'sudo docker build . -t jinjoo0402/connectus_spot:latest'
                }
            }
            post {
                    failure {
                      echo 'Spot docker image ${currentBuild.number} build failure !'
                    }
                    success {
                      echo 'Spot docker image ${currentBuild.number} build success !'
                    }
            }
    }
    stage('Docker Image Build (8) : User') {
            steps {
                dir('./backend/connectus/user-service') {
                  sh 'sudo docker build . -t jinjoo0402/connectus_user:latest'
                }
            }
            post {
                    failure {
                      echo 'User docker image ${currentBuild.number} build failure !'
                    }
                    success {
                      echo 'User docker image ${currentBuild.number} build success !'
                    }
            }
    }
    stage('Docker Image Build (9) : Walk') {
            steps {
                dir('./backend/connectus/walk-service') {
                  sh 'sudo docker build . -t jinjoo0402/connectus_walk:latest'
                }
            }
            post {
                    failure {
                      echo 'Walk docker image ${currentBuild.number} build failure !'
                    }
                    success {
                      echo 'Walk docker image ${currentBuild.number} build success !'
                    }
            }
    }
    
    stage('Login Docker Hub'){
          steps{
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin' // docker hub 로그인
          }
      }
    stage('Docker Image Push') {
            steps {
                      sh 'docker push jinjoo0402/connectus_likes:latest'
                      sh 'docker push jinjoo0402/connectus_user:latest'
                      sh 'docker push jinjoo0402/connectus_walk:latest'
                      sh 'docker push jinjoo0402/connectus_event:latest'
                      sh 'docker push jinjoo0402/connectus_spot:latest'
                      sh 'docker push jinjoo0402/connectus_gather:latest'
                      sh 'docker push jinjoo0402/connectus_post:latest'
                      sh 'docker push jinjoo0402/connectus_discovery:latest'
                      sh 'docker push jinjoo0402/connectus_apigateway:latest'
            }
            post {
                    failure {
                      echo 'Docker Image Push failure !'
                    }
                    success {
                      echo 'Docker image push success !'
                    }
            }
    }
    stage('Deploy') {
        steps([$class: 'BapSshPromotionPublisherPlugin']) {
            sshPublisher(
                continueOnError: false, failOnError: true,
                publishers: [
                    sshPublisherDesc(
                        configName: 'DEPLOY_SERVER',
                        verbose: true,
                        transfers: [
                            sshTransfer(
                              execCommand:
                                // TODO : docker-compose 로 변경 필요
                                // execCommand: 'docker compose up -d'
                                '''
                                docker rm -f $(docker ps -qa)
                                docker rmi $(docker images -q)

                                docker run -d --name spring-apigateway-service --net=host -p 8000:8000 -v /etc/localtime:/etc/localtime:ro jinjoo0402/connectus_apigateway:latest
                                docker run -d --name spring-discovery-service --net=host -p 8761:8761 -v /etc/localtime:/etc/localtime:ro jinjoo0402/connectus_discovery:latest
                                docker run -d --name spring-post-service --net=host -p 8101:8101 -v /etc/localtime:/etc/localtime:ro jinjoo0402/connectus_post:latest
                                docker run -d --name spring-gather-service --net=host -p 8102:8102 -v /etc/localtime:/etc/localtime:ro jinjoo0402/connectus_gather:latest
                                docker run -d --name spring-spot-service --net=host -p 8103:8103 -v /etc/localtime:/etc/localtime:ro jinjoo0402/connectus_spot:latest
                                docker run -d --name spring-event-service --net=host -p 8105:8105 -v /etc/localtime:/etc/localtime:ro jinjoo0402/connectus_event:latest
                                docker run -d --name spring-walk-service --net=host -p 8106:8106 -v /etc/localtime:/etc/localtime:ro jinjoo0402/connectus_walk:latest
                                docker run -d --name spring-user-service --net=host -p 8107:8107 -v /etc/localtime:/etc/localtime:ro jinjoo0402/connectus_user:latest
                                docker run -d --name spring-likes-service --net=host -p 8108:8108 -v /etc/localtime:/etc/localtime:ro jinjoo0402/connectus_likes:latest
                                '''
                                ),
                        ]
                    )
                ]
            )
        }
            post {
                success {
                    echo 'Deploy success'
                }
                failure {
                    echo 'Deploy failed'
                }
            }
    }
  }
}
